development:
  asquared_github_client_id:     50fb27ccfedd628ce6b6
  asquared_github_client_secret: a64af80da7d183d2fae6a3a5011876ee5267698d
  secret_key_base:               2113c51135785ed7f247a4b9685e5f2343121c955ab231add52949231671df43db1ba7f95404b603c7d6b9db7c68803656e1b176c4ad626f688586a8bfcaf524
  sendgrid_username:             jumpstartlab
  sendgrid_password:             NA

test:
  secret_key_base:               2113c51135785ed7f247a4b9685e5f2343121c955ab231add52949231671df43db1ba7f95404b603c7d6b9db7c68803656e1b176c4ad626f688586a8bfcaf524
  asquared_github_client_id:     SOME_ID
  asquared_github_client_secret: SOME_SECRET
  sendgrid_username:             jumpstartlab
  sendgrid_password:             SOME_PASSWORD

production:
  asquared_github_client_id:     <%= ENV['ASQUARED_GITHUB_CLIENT_ID'] %>
  asquared_github_client_secret: <%= ENV['ASQUARED_GITHUB_CLIENT_SECRET'] %>
  secret_key_base:               <%= ENV['SECRET_KEY_BASE'] %>
  sendgrid_username:             <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password:             <%= ENV['SENDGRID_PASSWORD'] %>
  aws_access_key_id:             <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:         <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
